<template lang="pug">
v-app
  .main
    video(autoplay muted loop id="schlimmVideo")
      source(src="./assets/videos/schlimm.webm")
    .main-text-center
      // p {{ message }}
    .icon-group
      font-awesome-icon(:icon="{prefix: 'fab', iconName: 'facebook' }" @click='facebook').icons-main
      font-awesome-icon(:icon="{prefix: 'fab', iconName: 'bandcamp' }" @click='bandcamp').icons-main
      font-awesome-icon(:icon="{prefix: 'far', iconName: 'envelope' }" @click='nachrichten = !nachrichten').icons-main
      font-awesome-icon(:icon="{prefix: 'far', iconName: 'calendar' }" @click='konzerte = !konzerte').icons-main
      template(v-if='playSound')
        font-awesome-icon(:icon="{prefix: 'fas', iconName: 'volume-up' }" @click='playSound = !playSound').icons-main
      template(v-else)
        font-awesome-icon(:icon="{prefix: 'fas', iconName: 'volume-off' }" @click='playSound = !playSound').icons-main
      v-slider(v-model="volume" color="#329676").slider-music-icon

  template(v-if="konzerte || nachrichten")
    v-dialog(v-model="showModal" max-width='500px')
      template(v-if="nachrichten")
        Nachrichten
      template(v-if="konzerte")
        Konzerte

</template>

<script>
import Nachrichten from './components/contact.vue'
import Konzerte from './components/concerts.vue'

export default {
  data: function (){
    return {
      message: "Schlimm",
      playSound: true,
      volume: 50,
      maxVolume: 100,
      clickedVolume: undefined,
      audio: {},
      nachrichten: false,
      konzerte: false,
      showModal: false
    }
  },
  components: {
    Nachrichten, Konzerte
  },
  computed: {
  },
  methods: {
    facebook(){
      window.open("https://www.facebook.com/Schlimm.Band");
    },
    bandcamp(){
      window.open("https://schlimmband.bandcamp.com/releases");
    },
    randomSong(){
      var song = Math.floor(Math.random() * 5) + 1;
      this.audio.pause();
      this.audio = new Audio(require('./assets/audios/' + song + '.mp3'));
    }
  },
  watch: {
    volume(){
      if (this.volume > this.maxVolume){
        this.volume = this.maxVolume;
      }
      this.audio.volume = this.volume/100;
      if (this.volume > 0){
        this.audio.play();
        this.playSound = true;
      }
    },
    playSound(){
      if (!this.playSound){
        this.clickedVolume = this.volume;
        this.volume = 0;
        this.randomSong();
      }
      if (this.playSound && (this.clickedVolume != undefined)){
        this.volume = this.clickedVolume;
      }
    },
    showModal(){
      if (!this.showModal){
        this.nachrichten = false
        this.konzerte = false
      }
    },
    nachrichten(){
      if (this.nachrichten){
        this.showModal = true
        this.konzerte = false
      }
    },
    konzerte(){
      if (this.konzerte){
        this.showModal = true
        this.nachrichten = false
      }
    }
  },
  created(){
    var audio = new Audio(require('./assets/audios/1.mp3'));
    this.playSound = false;
    this.audio = audio;
    this.audio.volume = this.volume/100;
  }
}
</script>

<style lang="sass">

#schlimmVideo
  position: absolute
  width: 100%
  height: 100%
  object-fit: cover

.main-text-center
  position: absolute
  left: 50%
  top: 30%
  -webkit-transform: translate(-50%, -50%)
  transform: translate(-50%, -50%)

  p
    font-size: 5em
    color: #329676
    font-family: 'Knewave', cursive
    animation: 30s beat infinite alternate
    letter-spacing: 4px
.icon-group
  color: #329676
  font-size: 3em
  position: absolute
  left: 50%
  bottom: 0%
  -webkit-transform: translate(-50%, -50%)
  transform: translate(-50%, -50%)
  width: 100%
  text-align: center

.icons-main
  margin: 0 2%
  cursor: pointer

.slider-music-icon
  position: absolute
  width: 50%
  left: 25%
  bottom: -70%



/* ----------------------------------------------
 * Generated by Animista on 2018-8-29 12:22:53
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-fwd-center
 * ----------------------------------------
 */

@keyframes beat
  0%
    transform: scale(1)
    text-shadow: 0 0 5px #329676
  25%
    transform: scale(1.05)
    text-shadow: 0 0 10px #329676
  50%
    transform: scale(.95)
    text-shadow: 0 0 5px #329676
  75%
    transform: scale(1.1)
    text-shadow: 0 0 15px #329676
  100%
    transform: scale(1)
    text-shadow: 0 0 5px #329676
</style>
